version: '3.8'

services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    command: gunicorn --timeout 0 breastwise.wsgi:application --bind 0.0.0.0:8000 
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/media
    expose:
      - "8000"
    env_file:
      - ./.env.prod

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
    ports:
      - "8000:80"
    depends_on:
      - web
volumes:
  static_volume:
  media_volume:
